version: '3.5'
services:
  personalization:
    container_name: personalization
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
